### ISSUE TITLE
More rows?

### ISSUE THREAD

**Issue by kinnala** [ttsirkia/neuvontajono#3]
This is a great tool, I used it successfully on a physics course with 350 students and the students liked it. So thanks a lot for your work! Nevertheless, I have a (seemingly?) simple suggestion for improving the tool for larger exercise sessions.

We frequently ran sessions in large halls with more than 10 rows. In the join queue form students were able to choose up to row 10 but I was not able to find a way to change the maximum number of rows.

In our larger sessions not everyone can fit into the first 10 rows. Having an option for changing this would be fantastic but even a larger fixed number (say up to 20 or 25) would help a lot.

I don't know TypeScript but I will now take a look at the source code to see if I am able to find a hardcoded maximum number of rows.

**Comment by kinnala** [comment]
Here is a reference to the maximum row 10: https://github.com/ttsirkia/neuvontajono/blob/7a527f7397113a3906bc03ba490602f69e0b1089/src/server/router/api/queue.ts#L35

max(10) would at least need to be changed to max(25). I don't know if it is enough.

**Comment by kinnala** [comment]
Here is another place which needs to be changed:
https://github.com/ttsirkia/neuvontajono/blob/7a527f7397113a3906bc03ba490602f69e0b1089/src/pages/queue.tsx#L476

**Comment by ttsirkia** [comment]
Thanks for the suggestion! Those places should be enough. Originally, in Maarintalo the number of ten rows was sufficient. I'll change this at the same time when merging the open PR.

However, I need to check with IT department who is currently running their instance of this app to get the latest version running.

**Comment by kinnala** [comment]
Thanks for your response!

I can also push internally at Aalto if you need support in getting the latest version running.

**Comment by ttsirkia** [comment]
Fixed in 819cafd578071e15512762e59d7c96faad9b9c86. I'll ask my ex-colleagues in Aalto if they could update the version.

**Comment by oseppala** [comment]
The system has been upgraded.
